version: "3"

services:
    app:
        container_name: ranepa_app
        restart: always
        build: .
        ports:
            - "3000:3000"
        links:
            - db
        environment:
            - PORT=3000
            - DB_USER=postgres
            - DB_PASS=123456
            - DB_ADDR=db:5432
            
    db:
        container_name: ranepa_database
        image: postgres
        ports:
            - "5432"
        environment:
            - POSTGRES_PASSWORD=123456
