version: "3"

services:
    app:
        container_name: ranepa_app
        restart: always
        build: .
        ports:
            - "3000:3000"
        links:
            - db

    db:
        container_name: ranepa_database
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - PORT = 3000
            - DB_USER = 'postgres'
            - DB_PASS = 123456
            - DB_ADDR = 127.0.0.1:5432
