name: Test

on:
  push:
    branches:
    - main

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Start database
      run: docker-compose up -d db

    - name: Restore database
      run: docker-compose run db pg_restore -d 'postgresql://postgres:123456@db' < ranepaback.sql

    - name: Launch app
      run: docker-compose up -d app
